spring.datasource.url=jdbc:mysql://avnadmin:AVNS_PsTBa43kVJi1kPVDjMq@mysql-27550bbc-db2026-1.l.aivencloud.com:22705/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_PsTBa43kVJi1kPVDjMq
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver